name: Create Pull Request on Test Success

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Run tests
      run: dotnet test TestStrings/TestStrings.csproj

  create-pull-request:
   needs: build
   if: github.ref == 'refs/heads/dev'
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4.1.1
   - name: Create Pull Request
     uses: repo-sync/pull-request@v2.12.1
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       source_branch: 'dev'
       destination_branch: 'main'
       pr_title: 'dev branch pr'
       pr_body: 'sikeres tesztek.'
